version: "3.8"

# Định nghĩa các mạng riêng biệt
networks:
  monitoring-network:
    name: monitoring-network
    driver: bridge

services:
  prometheus:
    image: prom/prometheus:v2.55.1 # Sử dụng phiên bản cụ thể thay vì latest
    container_name: prometheus
    user: "nobody"
    ports:
      - "127.0.0.1:9090:9090" # Chỉ cho phép truy cập từ localhost
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.time=15d"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    depends_on:
      - node_exporter
      - cadvisor
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: 312M
    networks:
      monitoring-network:
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:9090/-/healthy",
        ]
      interval: 30s
      timeout: 5s
      retries: 3

  grafana:
    image: grafana/grafana:9.5.2 # Sử dụng phiên bản cụ thể
    container_name: grafana
    user: "472"
    ports:
      - "4802:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana
    env_file:
      - .env
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_STARTTLS=true
      - GF_SMTP_SKIP_VERIFY=false
      - GF_SMTP_FROM_ADDRESS=${GF_SMTP_USER}
      - GF_SERVER_DOMAIN=${GF_SERVER_DOMAIN}
      - GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL}
      # Tăng cường bảo mật session
      - GF_SESSION_PROVIDER=memcached
      - GF_SESSION_PROVIDER_CONFIG=memcached:11211
      - GF_SECURITY_COOKIE_SECURE=true
      - GF_SECURITY_COOKIE_SAMESITE=lax
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: 312M
    networks:
      - monitoring-network
    depends_on:
      - prometheus
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/api/health",
        ]
      interval: 30s
      timeout: 5s
      retries: 3

  memcached:
    image: memcached:1.6.18-alpine
    container_name: memcached
    networks:
      - monitoring-network
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: 64M
    cpus: 0.10
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "11211"]
      interval: 30s
      timeout: 5s
      retries: 3

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: 312M
    command:
      - "--path.rootfs=/host"
    ports:
      - "127.0.0.1:9821:9100"
    networks:
      monitoring-network:
    pid: host
    restart: unless-stopped
    volumes:
      - "/:/host:ro,rslave"

  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: 312M
    networks:
      monitoring-network:

volumes:
  prometheus-data:
  grafana-data:
